### Create a task
POST http://localhost:8080/lists
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "name": "First list"
}

### Get all tasks for this user
GET http://localhost:8080/lists
Authorization: Bearer {{access_token}}

###

### Get all tasks for this user
GET http://localhost:8080/lists/2
Authorization: Bearer {{access_token}}

###
